algoritmo "Somar2Numeros"


var

  // seção de declaração das variaveis
  
  A : inteiro
  B, C : inteiro

inicio

// Fase de entrada de dados

//comando de saida de dados o

 escreva (" Digite um numero : ")
 // comando de entrada
 leia(A)
 
 escreva("digite um numero: ")
 leia(B)

  //processamento (<- sinal de atribuição)
  
  C <- A + B
  
  //Fase saida de dados
  escreva("o resultado é " , c)


fimalgoritmo